openapi: 3.1.0
info:
  version: 1.0.0
  title: API PFS
  contact:
    email: web@fletesdelsur.com
    url: https://fletesdelsur.com/
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: >
    API para la generación y consulta de Guías de Crédito

    # Alcances y limitantes

    Consulta de información de cuenta
    Consulta de coberturas por CP
    Cotización por charola general, politica de ventas y por medidas
    Generacíon de Guías
      - Guías con confirmación 
      - Confirmar Guía
      - Cancelar Guía sin confirmar


tags:
  - name: Autentificación
    description: Se requiere un Token de Autentificación Bearer obtenido del Portal de Crédito de PFS. Este Token se deberá agregar en un Header para su autorización.
  - name: Perfil
    description: Operaciones acerca de la cuenta de Crédito.
  - name: Tag
    description: This is a tag description.
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
paths:
  /profile:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/pathItem.yaml
  /pathItemWithExamples:
    $ref: paths/pathItemWithExamples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
